on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: webinar-dev
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
